### PR TITLE
Fixes and updates.

### LINKED ISSUE #32: Programming >2M Samples/sec on DAC seems to cause Giga board to hang
I've been able to reproduce this a couple of times.  If I take the example program for generating a sinewave and change the frequency to 48000*lut_size (about 3M samples per second), the program compiles and uploads with no error.  About two seconds later the board disconnects from the USB serial port and is no longer recognizable by my PC.  I have to double-tap the reset and reload a program in order to get out of this.  I see no "SOS" pattern on the LED.  Just silence.

What is the maximum samples per second for the DAC outputs?  Obviously for audio 2M samples per second is plenty.  I was just wondering.  If there is a hard limit, it might be good to either put a check in the code for values > 2M or at least something in the documentations saying "Don't do that".

I'm including the failing code below, but its just the sinewave example with the frequency increased to 48000*lut_size.

`// This example outputs a 32KHz sine wave on A12/DAC1.
#include <Arduino_AdvancedAnalog.h>

AdvancedDAC dac1(A13);

uint16_t lut[] = {
    0x0800,0x08c8,0x098f,0x0a52,0x0b0f,0x0bc5,0x0c71,0x0d12,0x0da7,0x0e2e,0x0ea6,0x0f0d,0x0f63,0x0fa7,0x0fd8,0x0ff5,
    0x0fff,0x0ff5,0x0fd8,0x0fa7,0x0f63,0x0f0d,0x0ea6,0x0e2e,0x0da7,0x0d12,0x0c71,0x0bc5,0x0b0f,0x0a52,0x098f,0x08c8,
    0x0800,0x0737,0x0670,0x05ad,0x04f0,0x043a,0x038e,0x02ed,0x0258,0x01d1,0x0159,0x00f2,0x009c,0x0058,0x0027,0x000a,
    0x0000,0x000a,0x0027,0x0058,0x009c,0x00f2,0x0159,0x01d1,0x0258,0x02ed,0x038e,0x043a,0x04f0,0x05ad,0x0670,0x0737
};

static size_t lut_size = sizeof(lut) / sizeof(lut[0]);

void setup() {
    Serial.begin(9600);
    if (!dac1.begin(AN_RESOLUTION_12, 48000 * lut_size, 64, 128)) {
        Serial.println("Failed to start DAC1 !");
        while (1);
    }
}

void loop() {
    static size_t lut_offs = 0;
    if (dac1.available()) {
        // Get a free buffer for writing.
        SampleBuffer buf = dac1.dequeue();
        // Write data to buffer.
        for (size_t i=0; i<buf.size(); i++, lut_offs++) {
            buf[i] =  lut[lut_offs % lut_size];
        }
        // Write the buffer to DAC.
        dac1.write(buf);
    }
}`

### LINKED ISSUE #35: DMA DAC intialization is unstable
While trying to port the Mozzi (Sound Synthesis) library to the Arduino Giga, I notice that DMA driven DAC seems to be quite fragile to set up, in some cases the DAC will simply fail to start.

Testcase: I can trip up the DAC_Sine_wave example by as little as uncommenting the ```Serial.begin()``` line. Now the very same sketch will work some but not all of the time (try resetting a couple of times).

After lots of trial and error, I think I have pinned this down to the double buffered dma setup around here:

https://github.com/arduino-libraries/Arduino_AdvancedAnalog/blob/80eeb61669f8c45105b973f8b400bb44de80db21/src/AdvancedDAC.cpp#L129

Quite obviously, first starting the DAC, then pausing it to enable double buffering, then restarting it seems like a hack (if justified) in the first place.

I managed to arrive at a robust sketch, by essentially copying the HAL_DAC_Start_DMA implementation from the HAL, but modifying it to set up double buffering right away (settings the correct flags, addresses, and starting DMA with HAL_DMAEx_MultiBufferStart_IT). Of course that makes for a *very* verbose solution. License-wise, I think it should be ok, as the HAL library appears to be BSD'ed.

Would the above make for an acceptable PR, do you have another idea on attacking the problem, or am I the only one to experience it?

### PR DESCRIPTION
**Pull request by iabdalkader**
* Fix DMA buffer Queue memory issues.
* Misc improvements to make DAC more robust. 
* Update Waveform_Generator.ino example. 
* Fixes #32 
* Fixes #35

### CODE REVIEW

**Comment by iabdalkader** [comment]
Hi @aentinger can you please review this and if it looks good, merge and do another release ? Thanks.

**Review by aentinger — COMMENTED** [review]
Inhowfar is the new buffer implementation "threadsafe"? I'm asking because I'm not seeing any locking :thinking: .

**Comment by aentinger** [comment]
Check, thanks for the clarification :+1:

**Review by aentinger — APPROVED** [review]
LGTM :+1:

**Pull request merged**
